
name: weekly-reports
on:
  schedule:
    - cron: "15 1 * * MON"  # Jeden Montag 01:15 UTC (~02:15/03:15 Berlin)
  workflow_dispatch:

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -r requirements.txt reportlab
      - name: Weekly PDF
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python smartsheet_reports_orchestrator.py weekly
      - name: Commit & push reports
        run: |
          git config user.email "bot@example.com"
          git config user.name "automation"
          git add -A reports/weekly
          git commit -m "Weekly report" || echo "No diff"
          git push || true
