name: Smartsheet Tracking and Reporting

on:
  # Daily tracking at midnight UTC
  schedule:
    - cron: '0 0 * * *'        # Daily tracking (midnight UTC)
    - cron: '0 1 * * MON'      # Weekly report (1 AM UTC on Monday)
    - cron: '0 2 1 * *'        # Monthly report (2 AM UTC on 1st of month)
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'track'
        type: choice
        options:
          - track
          - weekly-report
          - monthly-report
          - bootstrap

permissions:
  contents: write

jobs:
  daily-tracking:
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      - name: Run daily tracking
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add tracking_data/
          git commit -m "Update tracking data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

  weekly-report:
    if: github.event_name == 'schedule' && github.event.schedule == '0 1 * * MON'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      - name: Generate weekly report
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --weekly --previous

      - name: Commit report
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add reports/
          git commit -m "Add weekly report $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

  monthly-report:
    if: github.event_name == 'schedule' && github.event.schedule == '0 2 1 * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      - name: Generate monthly report
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --monthly --previous

      - name: Commit report
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add reports/
          git commit -m "Add monthly report $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

  manual-action:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      - name: Run track
        if: github.event.inputs.action == 'track'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py

      - name: Run weekly report
        if: github.event.inputs.action == 'weekly-report'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --weekly --previous

      - name: Run monthly report
        if: github.event.inputs.action == 'monthly-report'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --monthly --previous

      - name: Bootstrap
        if: github.event.inputs.action == 'bootstrap'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py --bootstrap

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add tracking_data/ reports/
          git commit -m "Manual action: ${{ github.event.inputs.action }} $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
