name: Smartsheet Diagnostic

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Diagnostic action to perform'
        required: true
        default: 'check'
        type: choice
        options:
          - check
          - force-track
          - update-state

permissions:
  contents: write

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv

      - name: Run diagnostic
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_diagnostic.py --${{ github.event.inputs.action }}

      - name: Commit changes
        if: github.event.inputs.action != 'check'
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add tracking_data/
          git commit -m "Diagnostic: ${{ github.event.inputs.action }} $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
