name: Smartsheet Tracking and Reporting

on:
  # Daily tracking at midnight UTC
  schedule:
    - cron: '0 0 * * *'        # Daily tracking (midnight UTC)
    - cron: '0 1 * * MON'      # Weekly report (1 AM UTC on Monday)
    - cron: '0 2 1 * *'        # Monthly report (2 AM UTC on 1st of month)
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'track'
        type: choice
        options:
          - track
          - weekly-report
          - monthly-report
          - bootstrap
          - reset
          - test-changes

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      - name: Run track
        if: github.event.inputs.action == 'track' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py

      - name: Run weekly report
        if: github.event.inputs.action == 'weekly-report' || github.event_name == 'schedule' && github.event.schedule == '0 1 * * MON'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --weekly --previous

      - name: Run monthly report
        if: github.event.inputs.action == 'monthly-report' || github.event_name == 'schedule' && github.event.schedule == '0 2 1 * *'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --monthly --previous

      - name: Run bootstrap
        if: github.event.inputs.action == 'bootstrap'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py --bootstrap

      - name: Reset state
        if: github.event.inputs.action == 'reset'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py --reset

      - name: Test changes
        if: github.event.inputs.action == 'test-changes'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          # First modify state to force changes
          python smartsheet_tracker.py --test
          # Then run tracking to detect those changes
          python smartsheet_tracker.py

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smartsheet-logs
          path: |
            smartsheet_tracker.log
            smartsheet_report.log

      - name: Commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          mkdir -p reports/weekly reports/monthly
          git add tracking_data/ reports/
          git commit -m "${{ github.event.inputs.action || 'track' }} $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
