name: smartsheet-tracker-nightly

on:
  schedule:
    # Nightly Datenerhebung (UTC)
    - cron: "10 0 * * *"
    # Weekly Report (montags, nach Nightly)
    - cron: "15 1 * * MON"
    # Monthly Report (1. des Monats, nach Nightly)
    - cron: "25 2 1 * *"
  workflow_dispatch:
    inputs:
      mode:
        description: Welche Aufgabe soll manuell laufen?
        required: true
        type: choice
        default: nightly
        options: [nightly, weekly, monthly, bootstrap]

# Wir committen PDFs/Logs ins Repo
permissions:
  contents: write

jobs:
  nightly:
    # Läuft bei nightly-Schedule oder manuell (mode==nightly)
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '10 0 * * *')
      || (github.event_name == 'workflow_dispatch' && inputs.mode == 'nightly')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt reportlab

      - name: Nightly tracker (inkrementell)
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python smartsheet_reports_orchestrator.py nightly

      - name: Commit & push tracker logs
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "automation"
          git add -A tracker_logs
          git commit -m "chore: nightly tracker update [skip ci]" || echo "No changes"
          git push || true

  weekly:
    # Läuft montags per Schedule oder manuell (mode==weekly)
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '15 1 * * MON')
      || (github.event_name == 'workflow_dispatch' && inputs.mode == 'weekly')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt reportlab

      - name: Build weekly PDF (letzte abgeschlossene ISO-Woche)
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python smartsheet_reports_orchestrator.py weekly

      - name: Commit & push weekly report
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "automation"
          git add -A reports/weekly
          git commit -m "chore: weekly report [skip ci]" || echo "No changes"
          git push || true

      - name: (Optional) Upload weekly PDFs to Smartsheet
        if: ${{ secrets.SMARTSHEET_TARGET_SHEET != '' && secrets.SMARTSHEET_ACCESS_TOKEN != '' }}
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python -m pip install smartsheet-python-sdk
          python smartsheet_upload_reports.py \
            --sheet-id ${{ secrets.SMARTSHEET_TARGET_SHEET }} \
            --glob "reports/weekly/**/*.pdf"

  monthly:
    # Läuft am 1. des Monats per Schedule oder manuell (mode==monthly)
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '25 2 1 * *')
      || (github.event_name == 'workflow_dispatch' && inputs.mode == 'monthly')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt reportlab

      - name: Build monthly PDF (voriger Kalendermonat)
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python smartsheet_reports_orchestrator.py monthly

      - name: Commit & push monthly report
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "automation"
          git add -A reports/monthly
          git commit -m "chore: monthly report [skip ci]" || echo "No changes"
          git push || true

      - name: (Optional) Upload monthly PDFs to Smartsheet
        if: ${{ secrets.SMARTSHEET_TARGET_SHEET != '' && secrets.SMARTSHEET_ACCESS_TOKEN != '' }}
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python -m pip install smartsheet-python-sdk
          python smartsheet_upload_reports.py \
            --sheet-id ${{ secrets.SMARTSHEET_TARGET_SHEET }} \
            --glob "reports/monthly/**/*.pdf"

  bootstrap:
    # Nur manuell starten (mode==bootstrap)
    if: github.event_name == 'workflow_dispatch' && inputs.mode == 'bootstrap'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt reportlab

      - name: Bootstrap last 3 months + build monthly PDFs
        env:
          SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        run: |
          python smartsheet_reports_orchestrator.py bootstrap --months 3

      - name: Commit & push tracker logs + monthly reports
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "automation"
          git add -A tracker_logs reports/monthly
          git commit -m "chore: bootstrap 3m + monthly PDFs [skip ci]" || echo "No changes"
          git push || true
