name: Smartsheet Tracker Nightly

on:
  schedule:
    - cron: '0 0 * * *'          # täglich 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: smartsheet-tracker-nightly
  cancel-in-progress: false

jobs:
  tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (mit Retry)
        uses: devops-infra/action-retry@v1
        with:
          retries: 3
          retry_wait_seconds: 10
          command: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: python smartsheet_date_change_tracker.py

      - name: Commit CSV snapshot(s)
        run: |
          set -e
          MONTH_YEAR=$(date +'%m.%Y')
          LOG_DIR="tracker_logs"
          LOG_FILE="${LOG_DIR}/date_changes_log_${MONTH_YEAR}.csv"
          BACKUP_FILE="${LOG_DIR}/date_backup.csv"

          git config user.name  "github-actions"
          git config user.email "actions@github.com"

          CHANGED=0
          if [ -f "$LOG_FILE" ]; then
            git add -f "$LOG_FILE"
            CHANGED=1
          fi
          if [ -f "$BACKUP_FILE" ]; then
            git add -f "$BACKUP_FILE"
            CHANGED=1
          fi

          if [ $CHANGED -eq 1 ]; then
            git commit -m "Update date change logs (${MONTH_YEAR})" || echo "No diff to commit"
            git push || echo "Push skipped"
          else
            echo "No CSV files to commit."
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: date-change-logs
          path: |
            tracker_logs/date_changes_log_*.csv
            tracker_logs/date_backup.csv
          if-no-files-found: ignore
