name: Smartsheet Tracker Nightly

on:
  schedule:
    - cron: '0 0 * * *'   # täglich 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: date-change-tracker
  cancel-in-progress: false

jobs:
  tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          mkdir -p tracker_logs
          python smartsheet_date_change_tracker.py

      - name: Commit CSV snapshot(s)
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"

          CHANGED=0
          git add -f tracker_logs/*.csv 2>/dev/null || true
          git add -f tracker_logs/date_backup.csv 2>/dev/null || true

          git diff --cached --quiet && echo "No changes" || (git commit -m "Nightly update logs" && CHANGED=1)
          if [ $CHANGED -eq 1 ]; then git push || echo "Push skipped"; fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: date-change-logs
          path: |
            tracker_logs/*.csv
          if-no-files-found: ignore
