name: Smartsheet Status Snapshot (manuell)

on:
  workflow_dispatch:  # nur manuell im Actions‑Tab

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install smartsheet-python-sdk python-dotenv

      - name: Create 30‑Day status snapshot
        run: python smartsheet_status_snapshot.py

      - name: Commit status files
        run: |
          DATE=$(date +'%Y-%m-%d')
          FILE1="status/status_snapshot_${DATE}.csv"
          FILE2="status/status_summary_${DATE}.csv"

          if [ -f "$FILE1" ] || [ -f "$FILE2" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add -f "$FILE1" "$FILE2"
            git commit -m "Status Reports ${DATE}" || echo "No changes to commit"
            git push
          else
            echo "⚠️ Keine Status-Dateien für ${DATE} gefunden – überspringe Commit."
          fi
