name: Smartsheet Status Snapshot & Report (manuell)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      - name: Create 30‑day snapshot & summary
        run: python smartsheet_status_snapshot.py

      - name: Generate PDF report
        run: python smartsheet_status_report.py

      - name: Commit CSVs and PDF
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Änderungen sichern, Remote holen, wiederherstellen
          git stash --include-untracked
          git pull --rebase origin main || true
          git stash pop || true

          DATE=$(date +'%Y-%m-%d')
          SNAP="status/status_snapshot_${DATE}.csv"
          SUMM="status/status_summary_${DATE}.csv"
          PDF="status/status_report_${DATE}.pdf"

          git add -f "$SNAP" "$SUMM" "$PDF"
          git commit -m "Status Reports & PDF ${DATE}" || echo "No changes to commit"
          git push
