name: Smartsheet Status Snapshot (manuell)

on:
  workflow_dispatch:  # nur manuell im Actions‑Tab

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install smartsheet-python-sdk python-dotenv

      - name: Create 30‑Day status snapshot
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: python smartsheet_status_snapshot.py

      - name: Commit status snapshot
        run: |
          DATE=$(date +'%Y-%m-%d')
          FILE="status_snapshot_${DATE}.csv"
          if [ -f "$FILE" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add -f "$FILE"
            git commit -m "Status‑Snapshot ${DATE}" || echo "No changes to commit"
            git push
          else
            echo "⚠️ Datei $FILE nicht gefunden – überspringe Commit."
          fi
