name: Smartsheet Weekly Changes

on:
  schedule:
    - cron: '0 0 * * MON'    # jeden Montag 00:00 UTC
  workflow_dispatch:        # manuell auslösbar

permissions:
  contents: write

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install smartsheet-python-sdk python-dotenv

      - name: Generate weekly report
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: python smartsheet_weekly_change_tracker.py

      - name: Commit weekly CSV (overwrite)
        run: |
          FILE="weekly/weekly_changes.csv"
          if [ -f "$FILE" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add -f "$FILE"
            git commit -m "Overwrite weekly_changes.csv ($(date +'%Y-%m-%d'))" || echo "No changes"
            git push
          else
            echo "⚠️ weekly_changes.csv not found, skipping commit."
          fi
